### PR TITLE
Increase copy-mode and alert legibility

### PR DESCRIPTION
**Pull request by roosta**
I finally switched from my half-baked tmux theme to srcery-tmux, and great job on this, a really well made theme. I found some tweaks I'd like to suggest to improve readability a bit when in copy-mode:
comparison

### CODE REVIEW

**Comment by roosta** [comment]
Oh yeah, almost forgot, did a change on the bell-style as well:
alert

**Review by MindTooth — APPROVED** [review]

**Comment by MindTooth** [comment]
Great, great. 😁

I’ve moved away from using it full time.  I don’t have the colors rendered correctly or gone all together. 😢

**Comment by roosta** [comment]
Out of curiosity, what exactly do you mean that the colors doesn't render correctly? Is it a problem with the terminal application, or do you do a lot of remote work or something else?

**Comment by MindTooth** [comment]
> Out of curiosity, what exactly do you mean that the colors doesn't render correctly? Is it a problem with the terminal application, or do you do a lot of remote work or something else?

Mangled colors in Vim (Vim term) and no colors in e.g. Newsboat.  I used it as my main terminal windows manager, as all the mappings were in memory.  Now I'm using kitty, but poorly so.  No good custom mappings by me, etc.  "Vanilla" experience.

[My config](https://gitlab.com/MindTooth/dots/-/blob/master/config/tmux/tmux.conf).  Not sure if I've not done it correctly, or what.  I used to work at some point, but lately not.  Tried searching for fixes, but none worked.

**Comment by roosta** [comment]
That sucks. I had a look at your config, and nothing really stands out, but from experience maybe change [this](https://gitlab.com/MindTooth/dots/-/blob/master/config/tmux/tmux.conf#L21). It might be worth trying to set it up to use the terminfo for kitty, it should have been installed together with the terminal package. More on that on the [arch wiki](https://wiki.archlinux.org/index.php/Tmux#24-bit_color). Other than that I can't think of anything that should be affecting colors.

EDIT: except for `default-terminal`, but that's what I got it set to as well (`tmux-256color`). If I change or remove this, vim colors aren't rendered correctly. From tmux manual:
>For tmux to work correctly, this must be set to ‘screen’, ‘tmux’ or a derivative of them.

**Comment by roosta** [comment]
Have you checked that the `tmux-256color` terminfo is present on your system? on arch its located `/usr/share/terminfo/t/tmux-256color`

**Comment by MindTooth** [comment]
I followed [this](https://github.com/tmux/tmux/issues/1257#issuecomment-581378716) to add to my `~/.terminfo` folder.

Might take a swing at it again.  Strange that it can't work. 🤔

**Comment by roosta** [comment]
hmm, it should've worked, but maybe the terminal doesn't recognize it or its location. Worth a go.

**Pull request merged**
